//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Level/Data/Input/StationaryInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Support
{
    public partial class @StationaryInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @StationaryInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""StationaryInput"",
    ""maps"": [
        {
            ""name"": ""FPS"",
            ""id"": ""ec781481-f084-4aba-880e-9f5745f3d2a9"",
            ""actions"": [
                {
                    ""name"": ""MovementX"",
                    ""type"": ""Value"",
                    ""id"": ""dd849214-1a36-4e18-be67-dd48c524a51c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press(pressPoint=1.401298E-45,behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MovementY"",
                    ""type"": ""Value"",
                    ""id"": ""733819d8-ffdd-4cdd-8987-75496f7841fb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""43cf1caf-3671-4806-88af-795e77aa560f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotationX"",
                    ""type"": ""Value"",
                    ""id"": ""5a3ee4a8-273c-4ec6-9365-bf182e3ab87b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotationY"",
                    ""type"": ""Value"",
                    ""id"": ""2412eaed-3ced-42ee-b47a-6489c7718896"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Utility"",
                    ""type"": ""PassThrough"",
                    ""id"": ""eddeaa98-a199-4516-929b-13d7ed6942d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""bd9b3406-2793-428b-b050-29c60df61eb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lean"",
                    ""type"": ""Value"",
                    ""id"": ""36b1d91a-ed42-45b9-962d-73f59779f8c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""a8aa11d8-733c-437c-b227-0b4a2def827c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""ac73df77-89b3-4605-a745-353c7c73c4a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""b6714786-76c1-429f-8ecc-3140071b4a87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DistortTheShutter"",
                    ""type"": ""Button"",
                    ""id"": ""f5b50951-d069-47f8-aae9-dc84c6a9caec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowAmountOfAmmo"",
                    ""type"": ""Button"",
                    ""id"": ""8ede40ba-b7f7-4944-9984-2acb40736b3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShutterDelay"",
                    ""type"": ""Button"",
                    ""id"": ""031ad4ac-d432-45b0-ab2c-09a15bc376e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""f1bdca15-a9f8-4b35-89c7-b20ed40a6d43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LongInteract"",
                    ""type"": ""Button"",
                    ""id"": ""5e54b899-d8fd-4a3b-97a1-e56683e3537c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""4998a9d8-5e78-4ad6-8f1a-04ada90b255b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstSlotInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""83bfe484-5274-4859-86dc-09a6445f39fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondSlotInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""17dc1a19-d6b5-4694-bd42-93e706e23b90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropGun"",
                    ""type"": ""Button"",
                    ""id"": ""70a5bc23-e79a-4199-9e34-1924684a18df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HideGun"",
                    ""type"": ""Button"",
                    ""id"": ""f77b2c21-8efe-498d-bc9a-7b3cd1b992fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b8e18f94-9a4c-4e4b-b05a-418f7dfb76fc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57ff375e-b251-470d-8973-b23ddefd6f3a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""46650f52-09c1-44fa-9179-eb6f654f65b2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""90ce448e-967a-48ff-9f54-5d2aab5da204"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""387d1fa8-f1af-4aea-bf9e-783321fbade7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""915cdfc2-2789-4b6a-ac91-571669833acd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""21bec5ff-f7ce-450e-85fd-c243c53f6488"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7691288d-ce11-492f-ba6f-ef04c292e51c"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""4f7bf01c-1628-4d16-8886-80473a117f7d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c0cfb2e6-d36e-4470-8a43-214ac4838624"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""59e0f6a7-f4e7-4ba9-96e5-e9c436eac5d9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""af5e9dd8-799f-419c-8720-01f85d5716c2"",
                    ""path"": ""<Mouse>/Delta/X"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotationX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ffb514b-ab83-4355-a624-d8091964e0ac"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=8)"",
                    ""groups"": """",
                    ""action"": ""RotationX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85ce53cc-f7a3-4e1a-8947-b3b24e20d811"",
                    ""path"": ""<Mouse>/Delta/Y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotationY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71283398-1fc5-439d-b032-4e01e758ef57"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed7e5b89-517c-4be0-9fd3-6eca66041d3a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5ff1afb-af36-4adb-bf2c-a71982bedf59"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""634e9c71-e5cf-45e8-998a-ff21fc8112cc"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lean"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b9b1e0f7-7194-41c3-8133-8c265268af9f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lean"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""37885d99-4697-47d3-a6d0-ad854c5f58df"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lean"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""7e1224b9-1064-441f-bdd3-0b6363ac6fc4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c906db06-f138-419d-ab36-0c40d103ec35"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0f6c2ea3-d154-49bf-a143-b8629230bfff"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""85022b76-8a10-44b6-ad00-4c3cec9de51e"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=8)"",
                    ""groups"": """",
                    ""action"": ""RotationY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftRightShoulders"",
                    ""id"": ""cd2a4d12-bdcf-48ef-936d-f8c3e7b558ba"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lean"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7ecce9d4-4205-4920-9c68-aeb7cff75547"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lean"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cb2d6f6b-6772-451d-8af5-76e37363422f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lean"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9d68842f-30fb-4f46-b7e6-c0c5eac818d7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f2bd9ef-c523-49a7-b447-d2ecbae84b2a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9831997-5134-4219-9662-b186565ebee4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c4ebac4-8006-463e-99e8-f45ae80c8e4c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14d51426-5ab9-430b-8bd9-f28be1414c9c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b63b821c-d2fa-48a9-b001-79ef770783d3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56a5a5b8-8128-4a4e-9068-cd164fa2492b"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DistortTheShutter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e15eee7-9dd2-43a2-8850-32381174df36"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DistortTheShutter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5cdb6b7-5f70-41e3-9742-a59d37a28c95"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddde6696-3a56-4966-b0b1-dafcdfe2b28a"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7621c6d2-e1e9-4870-aca7-45fa9066ee66"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38d544a0-92dc-403c-a575-a285cf2d81ca"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec33cce8-5c1c-4474-b4e2-a0858a0b9939"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSlotInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f1e3751-8b1d-44b1-808a-edd6e6152784"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSlotInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c4a8b67-308b-4550-9fc4-8d38d5a640b4"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSlotInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f475d26-63dc-4482-8ece-3df4301ac13d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSlotInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00292408-ce91-4535-b6c1-1665389a239c"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShutterDelay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d980d89c-a2f5-43e7-b9f2-1f12490c223f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShutterDelay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d304e820-efc5-4ab8-a32e-c4ee1071a948"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5685f858-cef8-4ba9-aafa-0c7448095897"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0827c61-bf15-48ce-97de-a78c35ab9b50"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LongInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db606165-a0b8-4f87-9d4a-6ce372f866be"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LongInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a66c7a5-5780-44ae-986f-27628427abe6"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HideGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8443558-4c6e-4cab-8396-3bfc8032eae1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowAmountOfAmmo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36744ba0-a3fc-440e-8e23-176bebcc5196"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowAmountOfAmmo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // FPS
            m_FPS = asset.FindActionMap("FPS", throwIfNotFound: true);
            m_FPS_MovementX = m_FPS.FindAction("MovementX", throwIfNotFound: true);
            m_FPS_MovementY = m_FPS.FindAction("MovementY", throwIfNotFound: true);
            m_FPS_Jump = m_FPS.FindAction("Jump", throwIfNotFound: true);
            m_FPS_RotationX = m_FPS.FindAction("RotationX", throwIfNotFound: true);
            m_FPS_RotationY = m_FPS.FindAction("RotationY", throwIfNotFound: true);
            m_FPS_Utility = m_FPS.FindAction("Utility", throwIfNotFound: true);
            m_FPS_Crouch = m_FPS.FindAction("Crouch", throwIfNotFound: true);
            m_FPS_Lean = m_FPS.FindAction("Lean", throwIfNotFound: true);
            m_FPS_Shoot = m_FPS.FindAction("Shoot", throwIfNotFound: true);
            m_FPS_Aim = m_FPS.FindAction("Aim", throwIfNotFound: true);
            m_FPS_Reload = m_FPS.FindAction("Reload", throwIfNotFound: true);
            m_FPS_DistortTheShutter = m_FPS.FindAction("DistortTheShutter", throwIfNotFound: true);
            m_FPS_ShowAmountOfAmmo = m_FPS.FindAction("ShowAmountOfAmmo", throwIfNotFound: true);
            m_FPS_ShutterDelay = m_FPS.FindAction("ShutterDelay", throwIfNotFound: true);
            m_FPS_Interact = m_FPS.FindAction("Interact", throwIfNotFound: true);
            m_FPS_LongInteract = m_FPS.FindAction("LongInteract", throwIfNotFound: true);
            m_FPS_OpenInventory = m_FPS.FindAction("OpenInventory", throwIfNotFound: true);
            m_FPS_FirstSlotInteraction = m_FPS.FindAction("FirstSlotInteraction", throwIfNotFound: true);
            m_FPS_SecondSlotInteraction = m_FPS.FindAction("SecondSlotInteraction", throwIfNotFound: true);
            m_FPS_DropGun = m_FPS.FindAction("DropGun", throwIfNotFound: true);
            m_FPS_HideGun = m_FPS.FindAction("HideGun", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // FPS
        private readonly InputActionMap m_FPS;
        private IFPSActions m_FPSActionsCallbackInterface;
        private readonly InputAction m_FPS_MovementX;
        private readonly InputAction m_FPS_MovementY;
        private readonly InputAction m_FPS_Jump;
        private readonly InputAction m_FPS_RotationX;
        private readonly InputAction m_FPS_RotationY;
        private readonly InputAction m_FPS_Utility;
        private readonly InputAction m_FPS_Crouch;
        private readonly InputAction m_FPS_Lean;
        private readonly InputAction m_FPS_Shoot;
        private readonly InputAction m_FPS_Aim;
        private readonly InputAction m_FPS_Reload;
        private readonly InputAction m_FPS_DistortTheShutter;
        private readonly InputAction m_FPS_ShowAmountOfAmmo;
        private readonly InputAction m_FPS_ShutterDelay;
        private readonly InputAction m_FPS_Interact;
        private readonly InputAction m_FPS_LongInteract;
        private readonly InputAction m_FPS_OpenInventory;
        private readonly InputAction m_FPS_FirstSlotInteraction;
        private readonly InputAction m_FPS_SecondSlotInteraction;
        private readonly InputAction m_FPS_DropGun;
        private readonly InputAction m_FPS_HideGun;
        public struct FPSActions
        {
            private @StationaryInput m_Wrapper;
            public FPSActions(@StationaryInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @MovementX => m_Wrapper.m_FPS_MovementX;
            public InputAction @MovementY => m_Wrapper.m_FPS_MovementY;
            public InputAction @Jump => m_Wrapper.m_FPS_Jump;
            public InputAction @RotationX => m_Wrapper.m_FPS_RotationX;
            public InputAction @RotationY => m_Wrapper.m_FPS_RotationY;
            public InputAction @Utility => m_Wrapper.m_FPS_Utility;
            public InputAction @Crouch => m_Wrapper.m_FPS_Crouch;
            public InputAction @Lean => m_Wrapper.m_FPS_Lean;
            public InputAction @Shoot => m_Wrapper.m_FPS_Shoot;
            public InputAction @Aim => m_Wrapper.m_FPS_Aim;
            public InputAction @Reload => m_Wrapper.m_FPS_Reload;
            public InputAction @DistortTheShutter => m_Wrapper.m_FPS_DistortTheShutter;
            public InputAction @ShowAmountOfAmmo => m_Wrapper.m_FPS_ShowAmountOfAmmo;
            public InputAction @ShutterDelay => m_Wrapper.m_FPS_ShutterDelay;
            public InputAction @Interact => m_Wrapper.m_FPS_Interact;
            public InputAction @LongInteract => m_Wrapper.m_FPS_LongInteract;
            public InputAction @OpenInventory => m_Wrapper.m_FPS_OpenInventory;
            public InputAction @FirstSlotInteraction => m_Wrapper.m_FPS_FirstSlotInteraction;
            public InputAction @SecondSlotInteraction => m_Wrapper.m_FPS_SecondSlotInteraction;
            public InputAction @DropGun => m_Wrapper.m_FPS_DropGun;
            public InputAction @HideGun => m_Wrapper.m_FPS_HideGun;
            public InputActionMap Get() { return m_Wrapper.m_FPS; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FPSActions set) { return set.Get(); }
            public void SetCallbacks(IFPSActions instance)
            {
                if (m_Wrapper.m_FPSActionsCallbackInterface != null)
                {
                    @MovementX.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnMovementX;
                    @MovementX.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnMovementX;
                    @MovementX.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnMovementX;
                    @MovementY.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnMovementY;
                    @MovementY.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnMovementY;
                    @MovementY.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnMovementY;
                    @Jump.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnJump;
                    @RotationX.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnRotationX;
                    @RotationX.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnRotationX;
                    @RotationX.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnRotationX;
                    @RotationY.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnRotationY;
                    @RotationY.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnRotationY;
                    @RotationY.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnRotationY;
                    @Utility.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnUtility;
                    @Utility.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnUtility;
                    @Utility.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnUtility;
                    @Crouch.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnCrouch;
                    @Crouch.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnCrouch;
                    @Crouch.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnCrouch;
                    @Lean.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnLean;
                    @Lean.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnLean;
                    @Lean.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnLean;
                    @Shoot.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnShoot;
                    @Shoot.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnShoot;
                    @Shoot.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnShoot;
                    @Aim.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnAim;
                    @Aim.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnAim;
                    @Aim.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnAim;
                    @Reload.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnReload;
                    @Reload.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnReload;
                    @Reload.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnReload;
                    @DistortTheShutter.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnDistortTheShutter;
                    @DistortTheShutter.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnDistortTheShutter;
                    @DistortTheShutter.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnDistortTheShutter;
                    @ShowAmountOfAmmo.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnShowAmountOfAmmo;
                    @ShowAmountOfAmmo.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnShowAmountOfAmmo;
                    @ShowAmountOfAmmo.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnShowAmountOfAmmo;
                    @ShutterDelay.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnShutterDelay;
                    @ShutterDelay.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnShutterDelay;
                    @ShutterDelay.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnShutterDelay;
                    @Interact.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnInteract;
                    @LongInteract.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnLongInteract;
                    @LongInteract.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnLongInteract;
                    @LongInteract.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnLongInteract;
                    @OpenInventory.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnOpenInventory;
                    @OpenInventory.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnOpenInventory;
                    @OpenInventory.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnOpenInventory;
                    @FirstSlotInteraction.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnFirstSlotInteraction;
                    @FirstSlotInteraction.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnFirstSlotInteraction;
                    @FirstSlotInteraction.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnFirstSlotInteraction;
                    @SecondSlotInteraction.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnSecondSlotInteraction;
                    @SecondSlotInteraction.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnSecondSlotInteraction;
                    @SecondSlotInteraction.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnSecondSlotInteraction;
                    @DropGun.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnDropGun;
                    @DropGun.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnDropGun;
                    @DropGun.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnDropGun;
                    @HideGun.started -= m_Wrapper.m_FPSActionsCallbackInterface.OnHideGun;
                    @HideGun.performed -= m_Wrapper.m_FPSActionsCallbackInterface.OnHideGun;
                    @HideGun.canceled -= m_Wrapper.m_FPSActionsCallbackInterface.OnHideGun;
                }
                m_Wrapper.m_FPSActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @MovementX.started += instance.OnMovementX;
                    @MovementX.performed += instance.OnMovementX;
                    @MovementX.canceled += instance.OnMovementX;
                    @MovementY.started += instance.OnMovementY;
                    @MovementY.performed += instance.OnMovementY;
                    @MovementY.canceled += instance.OnMovementY;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @RotationX.started += instance.OnRotationX;
                    @RotationX.performed += instance.OnRotationX;
                    @RotationX.canceled += instance.OnRotationX;
                    @RotationY.started += instance.OnRotationY;
                    @RotationY.performed += instance.OnRotationY;
                    @RotationY.canceled += instance.OnRotationY;
                    @Utility.started += instance.OnUtility;
                    @Utility.performed += instance.OnUtility;
                    @Utility.canceled += instance.OnUtility;
                    @Crouch.started += instance.OnCrouch;
                    @Crouch.performed += instance.OnCrouch;
                    @Crouch.canceled += instance.OnCrouch;
                    @Lean.started += instance.OnLean;
                    @Lean.performed += instance.OnLean;
                    @Lean.canceled += instance.OnLean;
                    @Shoot.started += instance.OnShoot;
                    @Shoot.performed += instance.OnShoot;
                    @Shoot.canceled += instance.OnShoot;
                    @Aim.started += instance.OnAim;
                    @Aim.performed += instance.OnAim;
                    @Aim.canceled += instance.OnAim;
                    @Reload.started += instance.OnReload;
                    @Reload.performed += instance.OnReload;
                    @Reload.canceled += instance.OnReload;
                    @DistortTheShutter.started += instance.OnDistortTheShutter;
                    @DistortTheShutter.performed += instance.OnDistortTheShutter;
                    @DistortTheShutter.canceled += instance.OnDistortTheShutter;
                    @ShowAmountOfAmmo.started += instance.OnShowAmountOfAmmo;
                    @ShowAmountOfAmmo.performed += instance.OnShowAmountOfAmmo;
                    @ShowAmountOfAmmo.canceled += instance.OnShowAmountOfAmmo;
                    @ShutterDelay.started += instance.OnShutterDelay;
                    @ShutterDelay.performed += instance.OnShutterDelay;
                    @ShutterDelay.canceled += instance.OnShutterDelay;
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                    @LongInteract.started += instance.OnLongInteract;
                    @LongInteract.performed += instance.OnLongInteract;
                    @LongInteract.canceled += instance.OnLongInteract;
                    @OpenInventory.started += instance.OnOpenInventory;
                    @OpenInventory.performed += instance.OnOpenInventory;
                    @OpenInventory.canceled += instance.OnOpenInventory;
                    @FirstSlotInteraction.started += instance.OnFirstSlotInteraction;
                    @FirstSlotInteraction.performed += instance.OnFirstSlotInteraction;
                    @FirstSlotInteraction.canceled += instance.OnFirstSlotInteraction;
                    @SecondSlotInteraction.started += instance.OnSecondSlotInteraction;
                    @SecondSlotInteraction.performed += instance.OnSecondSlotInteraction;
                    @SecondSlotInteraction.canceled += instance.OnSecondSlotInteraction;
                    @DropGun.started += instance.OnDropGun;
                    @DropGun.performed += instance.OnDropGun;
                    @DropGun.canceled += instance.OnDropGun;
                    @HideGun.started += instance.OnHideGun;
                    @HideGun.performed += instance.OnHideGun;
                    @HideGun.canceled += instance.OnHideGun;
                }
            }
        }
        public FPSActions @FPS => new FPSActions(this);
        public interface IFPSActions
        {
            void OnMovementX(InputAction.CallbackContext context);
            void OnMovementY(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnRotationX(InputAction.CallbackContext context);
            void OnRotationY(InputAction.CallbackContext context);
            void OnUtility(InputAction.CallbackContext context);
            void OnCrouch(InputAction.CallbackContext context);
            void OnLean(InputAction.CallbackContext context);
            void OnShoot(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnReload(InputAction.CallbackContext context);
            void OnDistortTheShutter(InputAction.CallbackContext context);
            void OnShowAmountOfAmmo(InputAction.CallbackContext context);
            void OnShutterDelay(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnLongInteract(InputAction.CallbackContext context);
            void OnOpenInventory(InputAction.CallbackContext context);
            void OnFirstSlotInteraction(InputAction.CallbackContext context);
            void OnSecondSlotInteraction(InputAction.CallbackContext context);
            void OnDropGun(InputAction.CallbackContext context);
            void OnHideGun(InputAction.CallbackContext context);
        }
    }
}
